apiVersion: v1
kind: Secret
metadata:
  name: ux-backend-proxy
  namespace: openshift-storage  # or your operator namespace
type: Opaque
stringData:
  session_secret: "KP7TThmSTZegSGmHuPKLnSaaAHSG3RSgqw6akBj0oVk"  # 30 character random string
