apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ux-backend-server
  namespace: openshift-storage
spec:
  podSelector:
    matchLabels:
      app: ux-backend-server
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-console
    ports:
    - protocol: TCP
      port: 8888
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-monitoring
    ports:
    - protocol: TCP
      port: 8888
