apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ceph-csi-cephfs-nodeplugin-csi-addons
  namespace: openshift-storage
spec:
  podSelector:
    matchLabels:
      app: openshift-storage.cephfs.csi.ceph.com-nodeplugin-csi-addons
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-storage
      podSelector:
        matchLabels:
          app: csi-addons-controller-manager
    ports:
    - protocol: TCP
      port: 9071
