---
name: commitlint

on:
  push:
    branches: ['main', 'release-*']
  pull_request:
    branches: ['*']

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      with:
        fetch-depth: 0

    - uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed #v6.2.1
      with:
        configFile: './.github/workflows/conf/commitlintrc.json'
        helpURL: |
          Some helpful links
          Contribution Guide -> https://github.com/red-hat-storage/odf-operator/blob/main/CONTRIBUTING.md#commit-structure
          Naming Conventions -> https://commitlint.js.org/#/concepts-commit-conventions
          Rules -> https://commitlint.js.org/#/reference-rules
          How to Write a Good Git Commit Message -> https://chris.beams.io/posts/git-commit
