---
name: github

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: z0al/dependent-issues@950226e7ca8fc43dc209a7febf67c655af3bdb43 #v1.5.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
