---
name: mirror-noobaa-upstream-images

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  mirror-noobaa-upstream-images:
    runs-on: ubuntu-latest
    if: >
      github.repository == 'red-hat-storage/odf-operator' &&
      github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      with:
        fetch-depth: 0

    - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 #v3.7.0
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_IO_USER }}
        password: ${{ secrets.QUAY_IO_PASS }}

    - name: mirror images
      run: hack/mirror-noobaa-images.sh
