---
name: yamllint
on:
  push:
    branches: ['main', 'release-*']
  pull_request:
    branches: ['*']
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      with:
        fetch-depth: 0

    - uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c #v3.1.1
      with:
        config_file: ./.github/workflows/conf/yamllint.yaml
        file_or_dir: .  # Recursive on all yaml files
